version: '3.1'
services:
  app:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      DATABASE_URL: mongodb://mongo:27017/appointments
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
